### ISSUE TITLE
how do I install it??

### ISSUE THREAD

**Issue by ralyodio** [mattrighetti/envelope#26]
I don't see any install instructions in README.md

**Comment by mattrighetti** [comment]
I used to have a `brew tap` for it but I've removed it temporarily. To install it you can download the binary file in the [latest release](https://github.com/mattrighetti/envelope/releases/tag/0.3.10) and move it to your `/usr/local/bin` folder or any other folder that is in your `$PATH`.

**Comment by mattrighetti** [comment]
More info added here 42e717e

**Comment by ralyodio** [comment]
Is there a way to install it with cargo?
